### ISSUE TITLE
Support Intel IPP and Deflate for Genomics 

### ISSUE THREAD

**Issue by nh13** [nh13/pbgzip#10]
We should be able to optionally compile with either [IPP](https://software.intel.com/en-us/intel-ipp) or [igzip](https://software.intel.com/en-us/articles/igzip-a-high-performance-deflate-compressor-with-optimizations-for-genomic-data) both provided by Intel.  We could see a 20-30% performance increase with using IPP's `zlib` while perhaps a 3.5x speedup with `igzip`.

**Comment by nh13** [comment]
`igzip` support is complete: https://github.com/nh13/pbgzip/pull/11

**Comment by chapmanb** [comment]
Brilliant Nils, very nice. @guillermo-carrasco tested your latest pbgzip fixes and things look great -- we incorporated it as a bioconda package and will start using it in bcbio as the default. Guillermo, any chance you want to test these latest speed ups? I'm not sure everything we'll need to compile but can also work to add the dependencies into bioconda so it's enabled by default once things look good.

**Comment by nh13** [comment]
@chapmanb  @guillermo-carrasco  I have added support for automake, which should make the build easier.  Check out the README for installing igzip and enabling it during configuring.

**Comment by chapmanb** [comment]
Nils -- thanks for all the additional documentation, this is really helpful. It sounds like the izip speed ups won't help us right now since we're using pbgzip to generate bgzipped fastqs for indexing with grabix, rather than making BAMs. We'll definitely explore this more if we start to use it for BAM prep. Thanks again for all this work on pbgzip.

**Comment by nh13** [comment]
Ipp is now supported (see: https://github.com/nh13/pbgzip/pull/16), which should give folks a 20-30% boost.

@chapmanb can I convince you that whenever you get a fastq, you immediately convert it to a BAM, even for unmapped data?  So many problems can be solved by having the right metadata embedded in the problem file (read group, reference, etc.).

**Comment by chapmanb** [comment]
Nils -- I'm convinced. The practical issue we have with using BAMs in this way is that we need to index the raw reads in chunks so we can parallelize alignments without needing to split the original file. Conceptually you might be able to do this with sam/bam and grabix but it suddenly gets a lot trickier with the header and converting into fastq to feed into alignments. If you know approaches to do this it would be great to migrate to a BAM-only workflow.

**Comment by nh13** [comment]
@chapmanb just to confirm, if you had a large BAM file, you want to have a tool that can give you some defined chunk in FASTQ format?  Say chunks like 1-10, 11-20, 21-30, ..., ?  

I think the way to do it, which could all be wrapped in a tool in Picard, is to simply create a dummy reference sequence with length `Integer.MAX_VALUE`, and then set each read's alignment position to the index in the original file (1, 2, 3, 4, ...).  We of course set the same index for ends of a pair.  Then, if you wanted records 2M-3M, you can just query the BAM file like `samtools view <in.bam> DUMMY:2000000-3000000`.

**Comment by nh13** [comment]
@chapmanb heres the tool in Picard I would use to create an unmapped BAM with dummy alignments: https://gist.github.com/nh13/5783fe6e6c8d2fbd6952.  Use `samtools view` or your favorite BAM viewer, and then pipe that into a tool like `SamToFastq` or the like.

**Comment by sambrightman** [comment]
Just to confirm, do you actually see the reported 20-30% speed improvement with IPP? I have built against (single-threaded) IPP and run 16 threads over a large pileup. This takes about 27 minutes normally, and with IPP the difference is within the noise (about 10s).

**Comment by nh13** [comment]
@sambrightman I did see the speed improvement, perhaps try with fewer threads (say 2 or 4) and see the bottleneck is elsewhere when running 16 threads?  That said, I don't use it personally as it is a bit of a pain to obtain, maintain, and pay for.

**Comment by sambrightman** [comment]
It appears to be free (see https://software.intel.com/en-us/articles/free-ipp). Did you use the single or threaded variant of IPP?

**Comment by nh13** [comment]
Honestly I don't recall, perhaps try both.  My apologies as it has been a while.
