### ISSUE TITLE
[pbgzip] Bad address: (null) when piping stdin

### ISSUE THREAD

**Issue by guillermo-carrasco** [nh13/pbgzip#7]
Hi,

We've been seeing "random" segfaults in `pbgzip` for a while, that we have already discussed, please refer to [this issue](https://github.com/chapmanb/bcbio-nextgen/issues/975) for context.

Fact is that I managed to isolate a file that makes `pbgzip` crash (but not `bgzip`). You can find the file [here](https://dl.dropboxusercontent.com/u/3046000/5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed). Some additional and useful information is that the problem seems to be when piping stdin. If I reproduce the exact command that our pipeline generates (this is piping stdin), then it crashes, but if I don’t pipe stdin but pass the file as an argument , then it works:

```
node01 ~/tests/pbgzip/work ~> cat /home/gcarrasco/tests/pbgzip/work/bedprep/5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed  | /home/gcarrasco/bin/pbgzip -n 16  -c > test_5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed.gz
[pbgzip] Bad address: (null)

 node01 ~/tests/pbgzip/work ~> /home/gcarrasco/bin/pbgzip /home/gcarrasco/tests/pbgzip/work/bedprep/5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed -n 16  -c > test_5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed.gz
```

We tried as well piping without buffering, and still fails:

```
 node01 ~/tests/pbgzip/work ~> stdbuf -i0 -o0 -e0 cat /home/gcarrasco/tests/pbgzip/work/bedprep/5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed  | /home/gcarrasco/bin/pbgzip -n 16  -c > test_5_2015-10-15_NA12878_samples-sort-callable-callableblocks.bed.gz
[pbgzip] Bad address: (null)
```

We though this information would be useful to try to spot the problem. 

I'm using a `pbgzip` that I compiled from the source code I got from this master branch. 

Thanks you very much!

**Comment by nh13** [comment]
Thanks for the bug report.  I will take a look at the test case shortly.

**Comment by nh13** [comment]
Fixed in #8, please report back if it does not work for you.

**Comment by guillermo-carrasco** [comment]
Thanks for the quick fix, it seems to work for that particular file, I'll re-launch a complete analysis and see how it goes.

Thanks again!

**Comment by guillermo-carrasco** [comment]
Hi @nh13 , I could run the same analysis that crashed before with the newly compiled `pbgzip` and it worked smoothly. Thanks!

**Comment by nh13** [comment]
Thanks for the report, I am glad it is working for you now.
